/*
 * tch_halobjs.h
 *
 *  Created on: 2014. 7. 20.
 *      Author: innocentevil
 */

#ifndef TCH_HALOBJS_H_
#define TCH_HALOBJS_H_

#include "stm32f4xx.h"
#include "tch_haldesc.h"

__attribute__((section(".data"))) static tch_gpio_descriptor GPIO_HWs[] = {
		{
				GPIOA,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOAEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOALPEN,
				0
		},
		{
				GPIOB,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOBEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOBLPEN,
				0
		},
		{
				GPIOC,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOCEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOCLPEN,
				0
		},
		{
				GPIOD,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIODEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIODLPEN,
				0
		},
		{
				GPIOE,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOEEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOELPEN,
				0
		},
		{
				GPIOF,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOFEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOFLPEN,
				0
		},
		{
				GPIOG,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOGEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOGLPEN,
				0
		},
		{
				GPIOH,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOHEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOHLPEN,
				0
		},
		{
				GPIOI,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOIEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOILPEN,
				0
		},
		{
				GPIOJ,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOJEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOJLPEN,
				0
		}
};

__attribute__((section(".data"))) static tch_ioInterrupt_descriptor IoInterrupt_HWs[] = {
		{
				NULL,
				NULL,
				INIT_LIST,
				EXTI0_IRQn
		},
		{
				NULL,
				NULL,
				INIT_LIST,
				EXTI1_IRQn
		},
		{
				NULL,
				NULL,
				INIT_LIST,
				EXTI2_IRQn
		},
		{
				NULL,
				NULL,
				INIT_LIST,
				EXTI3_IRQn
		},
		{
				NULL,
				NULL,
				INIT_LIST,
				EXTI4_IRQn
		},
		{
				NULL,
				NULL,
				INIT_LIST,
				EXTI9_5_IRQn
		},
		{
				NULL,
				NULL,
				INIT_LIST,
				EXTI9_5_IRQn
		},
		{
				NULL,
				NULL,
				INIT_LIST,
				EXTI9_5_IRQn
		},
		{
				NULL,
				NULL,
				INIT_LIST,
				EXTI9_5_IRQn
		},
		{
				NULL,
				NULL,
				INIT_LIST,
				EXTI9_5_IRQn
		},
		{
				NULL,
				NULL,
				INIT_LIST,
				EXTI15_10_IRQn
		},
		{
				NULL,
				NULL,
				INIT_LIST,
				EXTI15_10_IRQn
		},
		{
				NULL,
				NULL,
				INIT_LIST,
				EXTI15_10_IRQn
		},
		{
				NULL,
				INIT_LIST,
				EXTI15_10_IRQn
		},
		{
				NULL,
				NULL,
				INIT_LIST,
				EXTI15_10_IRQn
		},
		{
				NULL,
				NULL,
				INIT_LIST,
				EXTI15_10_IRQn
		}
};


/**
 * 	void*               _hw;
	uint32_t*           _clkenr;
	const uint32_t       clkmsk;
	uint32_t*           _lpclkenr;
	const uint32_t       lpcklmsk;
	uint32_t*           _isr;
	uint32_t*           _icr;
	uint32_t             ipos;
	IRQn_Type            irq;
 */
__attribute__((section(".data"))) static tch_dma_descriptor DMA_HWs[] ={
		{
				DMA1_Stream0,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->LISR,
				&DMA1->LIFCR,
				0,
				DMA1_Stream0_IRQn
		},
		{
				DMA1_Stream1,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->LISR,
				&DMA1->LIFCR,
				6,
				DMA1_Stream1_IRQn
		},
		{
				DMA1_Stream2,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->LISR,
				&DMA1->LIFCR,
				16,
				DMA1_Stream2_IRQn
		},
		{
				DMA1_Stream3,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->LISR,
				&DMA1->LIFCR,
				22,
				DMA1_Stream3_IRQn
		},
		{
				DMA1_Stream4,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->HISR,
				&DMA1->HIFCR,
				0,
				DMA1_Stream4_IRQn
		},
		{
				DMA1_Stream5,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->HISR,
				&DMA1->HIFCR,
				6,
				DMA1_Stream5_IRQn
		},
		{
				DMA1_Stream6,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->HISR,
				&DMA1->HIFCR,
				16,
				DMA1_Stream6_IRQn
		},
		{
				DMA1_Stream7,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->HISR,
				&DMA1->HIFCR,
				22,
				DMA1_Stream7_IRQn
		},
		{
				DMA2_Stream0,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA2->LISR,
				&DMA2->LIFCR,
				0,
				DMA2_Stream0_IRQn
		},
		{
				DMA2_Stream1,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA2EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA2LPEN,
				&DMA2->LISR,
				&DMA2->LIFCR,
				6,
				DMA2_Stream1_IRQn
		},
		{
				DMA2_Stream2,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA2EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA2LPEN,
				&DMA2->LISR,
				&DMA2->LIFCR,
				16,
				DMA2_Stream2_IRQn
		},
		{
				DMA2_Stream3,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA2EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA2LPEN,
				&DMA2->LISR,
				&DMA2->LIFCR,
				22,
				DMA2_Stream3_IRQn
		},
		{
				DMA2_Stream4,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA2EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA2LPEN,
				&DMA2->HISR,
				&DMA2->HIFCR,
				0,
				DMA2_Stream4_IRQn
		},
		{
				DMA2_Stream5,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA2EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA2LPEN,
				&DMA2->HISR,
				&DMA2->HIFCR,
				6,
				DMA2_Stream5_IRQn
		},
		{
				DMA2_Stream6,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA2EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA2LPEN,
				&DMA2->HISR,
				&DMA2->HIFCR,
				16,
				DMA2_Stream6_IRQn
		},
		{
				DMA2_Stream7,
				NULL,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA2EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA2LPEN,
				&DMA2->HISR,
				&DMA2->HIFCR,
				22,
				DMA2_Stream7_IRQn
		}
};


#endif /* TCH_HALOBJS_H_ */
