/*
 * tch_halobjs.h
 *
 *  Created on: 2014. 7. 20.
 *      Author: innocentevil
 */

#ifndef TCH_HALOBJS_H_
#define TCH_HALOBJS_H_

#include "stm32f4xx.h"
#include "tch_haldesc.h"

__attribute__((section(".data"))) static tch_gpio_descriptor GPIO_HWs[] = {
		{
				GPIOA,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOAEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOALPEN,
				0
		},
		{
				GPIOB,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOBEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOBLPEN,
				0
		},
		{
				GPIOC,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOCEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOCLPEN,
				0
		},
		{
				GPIOD,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIODEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIODLPEN,
				0
		},
		{
				GPIOE,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOEEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOELPEN,
				0
		},
		{
				GPIOF,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOFEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOFLPEN,
				0
		},
		{
				GPIOG,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOGEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOGLPEN,
				0
		},
		{
				GPIOH,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOHEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOHLPEN,
				0
		},
		{
				GPIOI,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOIEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOILPEN,
				0
		},
		{
				GPIOJ,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_GPIOJEN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_GPIOJLPEN,
				0
		}
};

__attribute__((section(".data"))) static tch_ioInterrupt_descriptor IoInterrupt_HWs[] = {
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI0_IRQn
		},
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI1_IRQn
		},
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI2_IRQn
		},
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI3_IRQn
		},
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI4_IRQn
		},
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI9_5_IRQn
		},
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI9_5_IRQn
		},
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI9_5_IRQn
		},
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI9_5_IRQn
		},
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI9_5_IRQn
		},
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI15_10_IRQn
		},
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI15_10_IRQn
		},
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI15_10_IRQn
		},
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI15_10_IRQn
		},
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI15_10_IRQn
		},
		{
				NULL,
				GENERIC_LIST_QUEUE_INIT,
				EXTI15_10_IRQn
		}
};


/**
 * 	void*               _hw;
	uint32_t*           _clkenr;
	const uint32_t       clkmsk;
	uint32_t*           _lpclkenr;
	const uint32_t       lpcklmsk;
	uint32_t*           _isr;
	uint32_t*           _icr;
	uint32_t             ipos;
	IRQn_Type            irq;
 */
static tch_dma_descriptor DMA_HWs[] ={
		{
				DMA1_Stream0,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->LISR,
				&DMA1->LIFCR,
				0,
				DMA1_Stream0_IRQn
		},
		{
				DMA1_Stream0,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->LISR,
				&DMA1->LIFCR,
				0,
				DMA1_Stream0_IRQn
		},
		{
				DMA1_Stream0,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->LISR,
				&DMA1->LIFCR,
				0,
				DMA1_Stream0_IRQn
		},
		{
				DMA1_Stream0,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->LISR,
				&DMA1->LIFCR,
				0,
				DMA1_Stream0_IRQn
		},
		{
				DMA1_Stream0,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->LISR,
				&DMA1->LIFCR,
				0,
				DMA1_Stream0_IRQn
		},
		{
				DMA1_Stream0,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->LISR,
				&DMA1->LIFCR,
				0,
				DMA1_Stream0_IRQn
		},
		{
				DMA1_Stream0,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->LISR,
				&DMA1->LIFCR,
				0,
				DMA1_Stream0_IRQn
		},
		{
				DMA1_Stream0,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->LISR,
				&DMA1->LIFCR,
				0,
				DMA1_Stream0_IRQn
		},
		{
				DMA1_Stream0,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->LISR,
				&DMA1->LIFCR,
				0,
				DMA1_Stream0_IRQn
		},
		{
				DMA1_Stream0,
				&RCC->AHB1ENR,
				RCC_AHB1ENR_DMA1EN,
				&RCC->AHB1LPENR,
				RCC_AHB1LPENR_DMA1LPEN,
				&DMA1->LISR,
				&DMA1->LIFCR,
				0,
				DMA1_Stream0_IRQn
		}
};


#endif /* TCH_HALOBJS_H_ */
